[package]
name = "play-song"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
id3 = "0.6.4"
rodio = "0.14.0"
walkdir = "2.3.2"

